name: Azure Static Web Apps CI/CD

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'deno.json'
      - 'deno.lock'
      - '.github/workflows/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'deno.json'
      - 'deno.lock'
      - '.github/workflows/**'

jobs:
  build_deploy_and_close_job:
    runs-on: ubuntu-latest-4-cores
    name: Build, Deploy, and Close Job
    container:
      image: denoland/deno:latest

    # Optimization: Set the default shell for all run steps to the faster 'sh'
    defaults:
      run:
        shell: sh

    steps:
      - name: Close Pull Request Environment
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_GRASS_0076A511E }}
          action: "close"

      - name: Checkout Code
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Hash source files
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        id: hash
        run: echo "files-hash=$(echo $(git rev-parse HEAD:src HEAD:public HEAD:deno.json HEAD:deno.lock) | git hash-object --stdin)" >> $GITHUB_OUTPUT

      - name: Cache Deno dependencies
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        uses: actions/cache@v4
        with:
          path: /deno-dir
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Cache build output
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        id: build-cache
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ steps.hash.outputs.files-hash }}

      - name: Build application
        if: (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')) && steps.build-cache.outputs.cache-hit != 'true'
        run: deno task build

      - name: Build And Deploy
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_GRASS_0076A511E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: "dist"
